package com.thaumicreborn.api.research;
public enum ResearchPurchaseResult {
    PURCHASED, UNKNOWN_RESEARCH, INACTIVE_RESEARCH, NOT_PURCHASABLE,
    ALREADY_COMPLETED, UNAVAILABLE, INSUFFICIENT_ASPECTS, MISSING_KNOWLEDGE
}
