modLoader="javafml"
loaderVersion="[47,)"
license="CC0-1.0"

[[mods]]
modId="thaumic_reborn_example"
version="${version}"
displayName="Thaumic Reborn Example Addon"
description='''Minimal compile-only API integration example.'''

[[dependencies.thaumic_reborn_example]]
modId="forge"
mandatory=true
versionRange="[47.4.10,48)"
ordering="NONE"
side="BOTH"

[[dependencies.thaumic_reborn_example]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.thaumic_reborn_example]]
modId="thaumcraftmodern"
mandatory=true
versionRange="[1.6.8,2)"
ordering="AFTER"
side="BOTH"
